[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
eth = "${RPC_URL_ETH}"
arb = "${RPC_URL_ARB}"
avax = "https://api.avax.network/ext/bc/C/rpc"
avaxtest = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
arb = { key = "${API_KEY_ARBISCAN}" }
avax= { key = "${API_KEY_SNOWTRACE" }
eth = { key = "${API_KEY_ETHERSCAN}" }
sepolia = { key = "${API_KEY_ETHERSCAN}" }
